Fix check-empty-networking-opsfile task
[#148525159]

diff --git a/tasks/check-empty-networking-opsfile b/tasks/check-empty-networking-opsfile
--- a/tasks/check-empty-networking-opsfile
+++ b/tasks/check-empty-networking-opsfile
@@ -7,8 +7,11 @@ pushd "cf-networking"
     exit 1
   fi
 
+  # grep returns non-zero exit status when no lines match
+  set +e
   let non_comment_lines=$(grep -Ecv '^#' manifest-generation/opsfiles/cf-networking.yml)
-  if [ "$non_comment_lines" -gt "0" ]; then
+  set -e
+  if [ "$non_comment_lines" -ne "0" ]; then
     echo "additions in cf-networking.yml should be merged in cf-deployment before shipping"
     exit 1
   fi
